name: Security Scan

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 10 * * *' # each day at 10:15 UTC

jobs:
  security-scan:
    name: Security Scan

    runs-on: ubuntu-latest

    continue-on-error: false

    strategy:
      matrix:
        branch-name:
          - 'release/8.0'
          - 'release/8.1'
          - 'release/8.2'
    steps:
      -   name: "Checkout code"
          uses: actions/checkout@v3
          with:
            ref: ${{ matrix.branch-name }}

      -   name: "PHP_VERSION Env"
          run: echo "PHP_VERSION=`grep "ARG PHP_VERSION" Dockerfile | cut -f 2 -d '"'`" > $GITHUB_ENV

      -   name: "BRANCH_SHA Env"
          run: echo "BRANCH_SHA=`git rev-parse HEAD`" >> $GITHUB_ENV

      -   name: Pull the image
          run: docker pull exozet/draft-docker-php:${{ env.PHP_VERSION }}

      -   name: Tag also with php:${{ env.PHP_VERSION }}
          run: docker tag exozet/draft-docker-php:${{ env.PHP_VERSION }} php-${{ env.PHP_VERSION }}
          
      -   name: Run Alpine Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: php-${{ env.PHP_VERSION }}
            format: 'table'
            exit-code: '0' # we don't break the build if vulnerabilities are included!
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

      -   if: contains(github.ref, 'refs/heads/main')
          name: Run Alpine Trivy vulnerability scanner and upload to github security tab
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: php-${{ env.PHP_VERSION }}
            format: 'sarif'
            output: 'trivy-results.sarif'

      -   if: contains(github.ref, 'refs/heads/main')
          name: Upload Alpine Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v2
          with:
            ref: refs/heads/${{ matrix.branch-name }}
            sha: ${{ env.BRANCH_SHA }}
            sarif_file: 'trivy-results.sarif'
      -   if: contains(github.ref, 'refs/heads/main')
          name: Run Snyk to check Docker images for vulnerabilities
          uses: snyk/actions/docker@master
          continue-on-error: true
          env:
             SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: exozet/draft-docker-php:${{ env.PHP_VERSION }}
            args: "--org=${{ secrets.SNYK_ORG }} --project-name=draft-docker-php --target-reference=${{ env.PHP_VERSION }}"
            command: monitor
